pipeline {
    agent any
    environment {
        IMAGE_NAME = 'htc-front-manager'
        REGISTRY_NAME = 'registry-htc.dilau.kz'
        SERVICE_NAME = 'htc-front-manager'
        SERVICE_PORT = '6001'
        registry = 'https://registry-htc.dilau.kz'
        registryCredential = 'registry-user'
    }
    tools {
        maven 'mvn-3.6.3'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Building image') {
            steps {
                script {
                    docker.withRegistry(registry, registryCredential) {
                        def customImage = docker.build("${env.IMAGE_NAME}:${env.BUILD_ID}")
                        customImage.push()
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying'
                script{
                    docker.withRegistry(registry, registryCredential) {
                        try {
                            sh '''
                                  SERVICES=$(docker service ls --filter name=${SERVICE_NAME} --quiet | wc -l)
                                  if [ "$SERVICES" -eq 0 ]; then
                                    docker service create --with-registry-auth --replicas 1 \
                                    --network consul-nw --network rolemanager-db-nw \
                                    --constraint node.role==worker \
                                    --env consul_host=consul \
                                    --name ${SERVICE_NAME} \
                                    --update-order start-first --stop-grace-period 60s \
                                    -p ${SERVICE_PORT}:8080 ${REGISTRY_NAME}/${IMAGE_NAME}:${BUILD_ID}
                                  else
                                    docker service update --with-registry-auth --update-order start-first --stop-grace-period 60s --image ${REGISTRY_NAME}/${IMAGE_NAME}:${BUILD_ID} ${SERVICE_NAME}
                                  fi
                                  '''
                        } catch(e) {
                            sh "docker service update --rollback ${SERVICE_NAME}"
                            error "Service update failed in production"
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'All good, we passed tests.'
        }
        failure {
            sh "docker service update --rollback ${SERVICE_NAME}"
        }
    }
}
